title: 'Singapore Accreditation Council'
title-abbreviated: SAC
description: 'Your Trusted Partner in Accreditation.'
url: 'https://www.sac-accreditation.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
collections:
    about:
        output: true
    industries:
        output: true
    services:
        output: true
    resources:
        output: true
    accredited-org:
        output: true
    courses:
        output: true
resources_name: newsroom
paginate: 12
paginate_path: '/newsroom/page:num'
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
include:
    - _redirects
favicon: /images/homepage/sac-esg-logo.png
google_analytics: UA-158199563-1
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
